name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Change working directory
        run: cd src
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/ctufit-thesis.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: src/ctufit-thesis.pdf
