name: Build and release

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile thesis
        uses: xu-cheng/latex-action@v2
        with:
          extra_system_packages: "gnuplot"
          root_file: ctufit-thesis.tex
          working_directory: src
          latexmk_shell_escape: true
      - name: Compile slides
        uses: xu-cheng/latex-action@v2
        with:
          root_file: slides.tex
          working_directory: slides
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
      - name: Publish the release 
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Aktuální verze"
          files: |
            src/ctufit-thesis.pdf
            slides/slides.pdf
